const ADD_COMMENT = 'ADD_COMMENT';
const DISHES_LOADING = 'DISHES_LOADING';
const DISHES_FAILED = 'DISHES_FAILED';
const ADD_DISHES = 'ADD_DISHES';
module.exports = {
    ADD_COMMENT,
    DISHES_LOADING,
    DISHES_FAILED,
    ADD_DISHES
}
