const ADD_COMMENT = 'ADD_COMMENT';
const DISHES_LOADING = 'DISHES_LOADING';
const DISHES_FAILED = 'DISHES_FAILED';
const ADD_DISHES = 'ADD_DISHES';
const ADD_COMMENTS = 'ADD_COMMENTS';
const COMMENTS_FAILED = 'COMMENTS_FAILED';
const PROMOS_LOADING = 'PROMOS_LOADING';
const ADD_PROMOS = 'ADD_PROMOS';
const PROMOS_FAILED = 'PROMOS_FAILED';
const ADD_LEADERS = 'ADD_LEADERS';
const LEADERS_FAILED = 'LEADERS_FAILED';
const LEADERS_LOADING = 'LEADERS_LOADING';
module.exports = {
    ADD_COMMENT,
    DISHES_LOADING,
    DISHES_FAILED,
    ADD_DISHES,
    ADD_COMMENTS,
    PROMOS_LOADING,
    ADD_PROMOS,
    PROMOS_FAILED,
    COMMENTS_FAILED,
    ADD_LEADERS,
    LEADERS_FAILED,
    LEADERS_LOADING
}
